### ISSUE TITLE
[Gazebo-gui failed and the x11vnc viewer displays black screen...

### ISSUE THREAD

**Issue by Currycurrycurry** [aws-deepracer-community/deepracer-simapp#117]

**Comment by Currycurrycurry** [comment]
I just built the docker image on my local PC and got this error. Anyone can help me? @mattcamp @ronzohan @richardfan1126 @jamesjennens

**Comment by larsll** [comment]
@Currycurrycurry - you need to add more information, including at least parts of your robomaker logs.

**Comment by Currycurrycurry** [comment]
root@51be3f79f767:/opt/install/Deepracer_Gazebo_Simulator/simulation_ws# roslaunch deepracer_simulation racetrack_with_racecar.launch world_name:=hard_track
... logging to /root/.ros/log/6d473286-403c-11ec-b548-0242ac110002/roslaunch-51be3f79f767-19198.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://51be3f79f767:44741/

SUMMARY
========

PARAMETERS
 * /gazebo/enable_ros_network: True
 * /racecar/joint_state_controller/publish_rate: 10
 * /racecar/joint_state_controller/type: joint_state_contr...
 * /racecar/left_front_wheel_velocity_controller/joint: left_front_wheel_...
 * /racecar/left_front_wheel_velocity_controller/pid/d: 0.0
 * /racecar/left_front_wheel_velocity_controller/pid/i: 0.0
 * /racecar/left_front_wheel_velocity_controller/pid/i_clamp: 0.0
 * /racecar/left_front_wheel_velocity_controller/pid/p: 0.5
 * /racecar/left_front_wheel_velocity_controller/type: effort_controller...
 * /racecar/left_rear_wheel_velocity_controller/joint: left_rear_wheel_j...
 * /racecar/left_rear_wheel_velocity_controller/pid/d: 0.0
 * /racecar/left_rear_wheel_velocity_controller/pid/i: 0.0
 * /racecar/left_rear_wheel_velocity_controller/pid/i_clamp: 0.0
 * /racecar/left_rear_wheel_velocity_controller/pid/p: 1.0
 * /racecar/left_rear_wheel_velocity_controller/type: effort_controller...
 * /racecar/left_steering_hinge_position_controller/joint: left_steering_hin...
 * /racecar/left_steering_hinge_position_controller/pid/d: 0.5
 * /racecar/left_steering_hinge_position_controller/pid/i: 0.0
 * /racecar/left_steering_hinge_position_controller/pid/p: 1.0
 * /racecar/left_steering_hinge_position_controller/type: effort_controller...
 * /racecar/right_front_wheel_velocity_controller/joint: right_front_wheel...
 * /racecar/right_front_wheel_velocity_controller/pid/d: 0.0
 * /racecar/right_front_wheel_velocity_controller/pid/i: 0.0
 * /racecar/right_front_wheel_velocity_controller/pid/i_clamp: 0.0
 * /racecar/right_front_wheel_velocity_controller/pid/p: 0.5
 * /racecar/right_front_wheel_velocity_controller/type: effort_controller...
 * /racecar/right_rear_wheel_velocity_controller/joint: right_rear_wheel_...
 * /racecar/right_rear_wheel_velocity_controller/pid/d: 0.0
 * /racecar/right_rear_wheel_velocity_controller/pid/i: 0.0
 * /racecar/right_rear_wheel_velocity_controller/pid/i_clamp: 0.0
 * /racecar/right_rear_wheel_velocity_controller/pid/p: 1.0
 * /racecar/right_rear_wheel_velocity_controller/type: effort_controller...
 * /racecar/right_steering_hinge_position_controller/joint: right_steering_hi...
 * /racecar/right_steering_hinge_position_controller/pid/d: 0.5
 * /racecar/right_steering_hinge_position_controller/pid/i: 0.0
 * /racecar/right_steering_hinge_position_controller/pid/p: 1.0
 * /racecar/right_steering_hinge_position_controller/type: effort_controller...
 * /robot_description: <?xml version="1....
 * /rosdistro: melodic
 * /rosversion: 1.14.12
 * /use_sim_time: True

NODES
  /
    better_odom (topic_tools/relay)
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    racecar_spawn (gazebo_ros/spawn_model)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    servo_commands (deepracer_simulation/servo_commands.py)
  /racecar/
    controller_manager (controller_manager/spawner)

auto-starting new master
process[master]: started with pid [19211]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 6d473286-403c-11ec-b548-0242ac110002
process[rosout-1]: started with pid [19222]
started core service [/rosout]
process[gazebo-2]: started with pid [19225]
process[gazebo_gui-3]: started with pid [19233]
process[racecar_spawn-4]: started with pid [19267]
process[racecar/controller_manager-5]: started with pid [19299]
ERROR: cannot launch node of type [robot_state_publisher/robot_state_publisher]: robot_state_publisher
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/opt/install/Deepracer_Gazebo_Simulator/simulation_ws/install/deepracer_simulation/share
ROS path [2]=/opt/install/Deepracer_Gazebo_Simulator/simulation_ws/install/deepracer_interpreter/share
ROS path [3]=/opt/install/Deepracer_Gazebo_Simulator/simulation_ws/install/deepracer_msgs/share
ROS path [4]=/opt/ros/melodic/share
process[servo_commands-7]: started with pid [19300]
[ INFO] [1636338883.022119558]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1636338883.023514830]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1636338883.030199443]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1636338883.031334300]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
process[better_odom-8]: started with pid [19307]
Traceback (most recent call last):
  File "/opt/install/Deepracer_Gazebo_Simulator/simulation_ws/install/deepracer_simulation/lib/deepracer_simulation/servo_commands.py", line 7, in <module>
    from ackermann_msgs.msg import AckermannDriveStamped
ImportError: No module named ackermann_msgs.msg
[INFO] [1636338883.177870, 0.000000]: Controller Spawner: Waiting for service controller_manager/load_controller
[ INFO] [1636338883.209596140]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1636338883.224065129]: Physics dynamic reconfigure ready.
[servo_commands-7] process has died [pid 19300, exit code 1, cmd /opt/install/Deepracer_Gazebo_Simulator/simulation_ws/install/deepracer_simulation/lib/deepracer_simulation/servo_commands.py /racecar/ackermann_cmd_mux/output:=/vesc/low_level/ackermann_cmd_mux/output __name:=servo_commands __log:=/root/.ros/log/6d473286-403c-11ec-b548-0242ac110002/servo_commands-7.log].
log file: /root/.ros/log/6d473286-403c-11ec-b548-0242ac110002/servo_commands-7*.log
[INFO] [1636338883.443967, 0.000000]: Loading model XML from ros parameter robot_description
[INFO] [1636338883.450150, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[INFO] [1636338883.452360, 0.000000]: Calling service /gazebo/spawn_urdf_model
[INFO] [1636338883.630170, 0.354000]: Spawn status: SpawnModel: Successfully spawned entity
[ INFO] [1636338883.648277084, 0.354000000]: Loading gazebo_ros_control plugin
[ INFO] [1636338883.648383753, 0.354000000]: Starting gazebo_ros_control plugin in namespace: /racecar
[ INFO] [1636338883.648808355, 0.354000000]: gazebo_ros_control plugin is waiting for model URDF in parameter [/robot_description] on the ROS param server.
Segmentation fault (core dumped)
[gazebo_gui-3] process has died [pid 19233, exit code 139, cmd /opt/ros/melodic/lib/gazebo_ros/gzclient __name:=gazebo_gui __log:=/root/.ros/log/6d473286-403c-11ec-b548-0242ac110002/gazebo_gui-3.log].
log file: /root/.ros/log/6d473286-403c-11ec-b548-0242ac110002/gazebo_gui-3*.log
[ WARN] [1636338883.758633311, 0.354000000]: Deprecated syntax, please prepend 'hardware_interface/' to 'EffortJointInterface' within the <hardwareInterface> tag in joint 'left_rear_wheel_joint'.
[ WARN] [1636338883.759353511, 0.354000000]: Deprecated syntax, please prepend 'hardware_interface/' to 'EffortJointInterface' within the <hardwareInterface> tag in joint 'right_rear_wheel_joint'.
[ WARN] [1636338883.759677192, 0.354000000]: Deprecated syntax, please prepend 'hardware_interface/' to 'EffortJointInterface' within the <hardwareInterface> tag in joint 'left_steering_hinge_joint'.
[ WARN] [1636338883.759944569, 0.354000000]: Deprecated syntax, please prepend 'hardware_interface/' to 'EffortJointInterface' within the <hardwareInterface> tag in joint 'right_steering_hinge_joint'.
[ WARN] [1636338883.760221676, 0.354000000]: Deprecated syntax, please prepend 'hardware_interface/' to 'EffortJointInterface' within the <hardwareInterface> tag in joint 'left_front_wheel_joint'.
[ WARN] [1636338883.760429437, 0.354000000]: Deprecated syntax, please prepend 'hardware_interface/' to 'EffortJointInterface' within the <hardwareInterface> tag in joint 'right_front_wheel_joint'.
[ INFO] [1636338883.763059896, 0.354000000]: Loaded gazebo_ros_control.
******* World name is: hard_track *********
[INFO] [1636338883.781887, 0.367000]: Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [1636338883.783763, 0.369000]: Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [1636338883.785333, 0.371000]: Loading controller: left_rear_wheel_velocity_controller
[ERROR] [1636338883.787583493, 0.373000000]: Could not load controller 'left_rear_wheel_velocity_controller' because controller type 'effort_controllers/JointVelocityController' does not exist.
[ERROR] [1636338883.787624385, 0.373000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
[racecar_spawn-4] process has finished cleanly
log file: /root/.ros/log/6d473286-403c-11ec-b548-0242ac110002/racecar_spawn-4*.log
[ERROR] [1636338884.788690, 1.373000]: Failed to load left_rear_wheel_velocity_controller
[INFO] [1636338884.790131, 1.374000]: Loading controller: right_rear_wheel_velocity_controller
[ERROR] [1636338884.792730122, 1.377000000]: Could not load controller 'right_rear_wheel_velocity_controller' because controller type 'effort_controllers/JointVelocityController' does not exist.
[ERROR] [1636338884.792763911, 1.377000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
[ERROR] [1636338885.794029, 2.376000]: Failed to load right_rear_wheel_velocity_controller
[INFO] [1636338885.795082, 2.377000]: Loading controller: left_front_wheel_velocity_controller
[ERROR] [1636338885.797091131, 2.379000000]: Could not load controller 'left_front_wheel_velocity_controller' because controller type 'effort_controllers/JointVelocityController' does not exist.
[ERROR] [1636338885.797134029, 2.379000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
[ERROR] [1636338886.798109, 3.379000]: Failed to load left_front_wheel_velocity_controller
[INFO] [1636338886.799236, 3.380000]: Loading controller: right_front_wheel_velocity_controller
[ERROR] [1636338886.801278064, 3.382000000]: Could not load controller 'right_front_wheel_velocity_controller' because controller type 'effort_controllers/JointVelocityController' does not exist.
[ERROR] [1636338886.801301457, 3.382000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
[ERROR] [1636338887.802141, 4.381000]: Failed to load right_front_wheel_velocity_controller
[INFO] [1636338887.803262, 4.382000]: Loading controller: left_steering_hinge_position_controller
[ERROR] [1636338887.805312646, 4.384000000]: Could not load controller 'left_steering_hinge_position_controller' because controller type 'effort_controllers/JointPositionController' does not exist.
[ERROR] [1636338887.805339247, 4.384000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
[ERROR] [1636338888.806109, 5.384000]: Failed to load left_steering_hinge_position_controller
[INFO] [1636338888.807202, 5.385000]: Loading controller: right_steering_hinge_position_controller
[ERROR] [1636338888.809172104, 5.387000000]: Could not load controller 'right_steering_hinge_position_controller' because controller type 'effort_controllers/JointPositionController' does not exist.
[ERROR] [1636338888.809195991, 5.387000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
[ERROR] [1636338889.810089, 6.386000]: Failed to load right_steering_hinge_position_controller
[INFO] [1636338889.811059, 6.387000]: Loading controller: joint_state_controller
[ERROR] [1636338889.812874163, 6.389000000]: Could not load controller 'joint_state_controller' because controller type 'joint_state_controller/JointStateController' does not exist.
[ERROR] [1636338889.812899368, 6.389000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
[ERROR] [1636338890.814110, 7.388000]: Failed to load joint_state_controller
[INFO] [1636338890.815278, 7.390000]: Controller Spawner: Loaded controllers: 
[INFO] [1636338890.818296, 7.393000]: Started controllers: 
^C[better_odom-8] killing on exit
[racecar/controller_manager-5] killing on exit
[gazebo-2] killing on exit
[INFO] [1636338966.230223, 82.678000]: Shutting down spawner. Stopping and unloading controllers...
[INFO] [1636338966.231931, 82.680000]: Stopping all controllers...
[racecar/controller_manager-5] escalating to SIGTERM
[gazebo-2] escalating to SIGTERM
[WARN] [1636338981.252516, 82.680000]: Controller Spawner error while taking down controllers: transport error completing service call: receive_once[/racecar/controller_manager/switch_controller]: unexpected error [Errno 4] Interrupted system call
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by Currycurrycurry** [comment]
> root@51be3f79f767:/opt/install/Deepracer_Gazebo_Simulator/simulation_ws# roslaunch deepracer_simulation racetrack_with_racecar.launch world_name:=hard_track ... logging to /root/.ros/log/6d473286-403c-11ec-b548-0242ac110002/roslaunch-51be3f79f767-19198.log Checking log directory for disk usage. This may take a while. Press Ctrl-C to interrupt Done checking log file disk usage. Usage is <1GB.
> 
> started roslaunch server http://51be3f79f767:44741/
> # SUMMARY
> 
> PARAMETERS
> 
>     * /gazebo/enable_ros_network: True
> 
>     * /racecar/joint_state_controller/publish_rate: 10
> 
>     * /racecar/joint_state_controller/type: joint_state_contr...
> 
>     * /racecar/left_front_wheel_velocity_controller/joint: left_front_wheel_...
> 
>     * /racecar/left_front_wheel_velocity_controller/pid/d: 0.0
> 
>     * /racecar/left_front_wheel_velocity_controller/pid/i: 0.0
> 
>     * /racecar/left_front_wheel_velocity_controller/pid/i_clamp: 0.0
> 
>     * /racecar/left_front_wheel_velocity_controller/pid/p: 0.5
> 
>     * /racecar/left_front_wheel_velocity_controller/type: effort_controller...
> 
>     * /racecar/left_rear_wheel_velocity_controller/joint: left_rear_wheel_j...
> 
>     * /racecar/left_rear_wheel_velocity_controller/pid/d: 0.0
> 
>     * /racecar/left_rear_wheel_velocity_controller/pid/i: 0.0
> 
>     * /racecar/left_rear_wheel_velocity_controller/pid/i_clamp: 0.0
> 
>     * /racecar/left_rear_wheel_velocity_controller/pid/p: 1.0
> 
>     * /racecar/left_rear_wheel_velocity_controller/type: effort_controller...
> 
>     * /racecar/left_steering_hinge_position_controller/joint: left_steering_hin...
> 
>     * /racecar/left_steering_hinge_position_controller/pid/d: 0.5
> 
>     * /racecar/left_steering_hinge_position_controller/pid/i: 0.0
> 
>     * /racecar/left_steering_hinge_position_controller/pid/p: 1.0
> 
>     * /racecar/left_steering_hinge_position_controller/type: effort_controller...
> 
>     * /racecar/right_front_wheel_velocity_controller/joint: right_front_wheel...
> 
>     * /racecar/right_front_wheel_velocity_controller/pid/d: 0.0
> 
>     * /racecar/right_front_wheel_velocity_controller/pid/i: 0.0
> 
>     * /racecar/right_front_wheel_velocity_controller/pid/i_clamp: 0.0
> 
>     * /racecar/right_front_wheel_velocity_controller/pid/p: 0.5
> 
>     * /racecar/right_front_wheel_velocity_controller/type: effort_controller...
> 
>     * /racecar/right_rear_wheel_velocity_controller/joint: right_rear_wheel_...
> 
>     * /racecar/right_rear_wheel_velocity_controller/pid/d: 0.0
> 
>     * /racecar/right_rear_wheel_velocity_controller/pid/i: 0.0
> 
>     * /racecar/right_rear_wheel_velocity_controller/pid/i_clamp: 0.0
> 
>     * /racecar/right_rear_wheel_velocity_controller/pid/p: 1.0
> 
>     * /racecar/right_rear_wheel_velocity_controller/type: effort_controller...
> 
>     * /racecar/right_steering_hinge_position_controller/joint: right_steering_hi...
> 
>     * /racecar/right_steering_hinge_position_controller/pid/d: 0.5
> 
>     * /racecar/right_steering_hinge_position_controller/pid/i: 0.0
> 
>     * /racecar/right_steering_hinge_position_controller/pid/p: 1.0
> 
>     * /racecar/right_steering_hinge_position_controller/type: effort_controller...
> 
>     * /robot_description: <?xml version="1....
> 
>     * /rosdistro: melodic
> 
>     * /rosversion: 1.14.12
> 
>     * /use_sim_time: True
> 
> 
> NODES / better_odom (topic_tools/relay) gazebo (gazebo_ros/gzserver) gazebo_gui (gazebo_ros/gzclient) racecar_spawn (gazebo_ros/spawn_model) robot_state_publisher (robot_state_publisher/robot_state_publisher) servo_commands (deepracer_simulation/servo_commands.py) /racecar/ controller_manager (controller_manager/spawner)
> 
> auto-starting new master process[master]: started with pid [19211] ROS_MASTER_URI=http://localhost:11311
> 
> setting /run_id to 6d473286-403c-11ec-b548-0242ac110002 process[rosout-1]: started with pid [19222] started core service [/rosout] process[gazebo-2]: started with pid [19225] process[gazebo_gui-3]: started with pid [19233] process[racecar_spawn-4]: started with pid [19267] process[racecar/controller_manager-5]: started with pid [19299] ERROR: cannot launch node of type [robot_state_publisher/robot_state_publisher]: robot_state_publisher ROS path [0]=/opt/ros/melodic/share/ros ROS path [1]=/opt/install/Deepracer_Gazebo_Simulator/simulation_ws/install/deepracer_simulation/share ROS path [2]=/opt/install/Deepracer_Gazebo_Simulator/simulation_ws/install/deepracer_interpreter/share ROS path [3]=/opt/install/Deepracer_Gazebo_Simulator/simulation_ws/install/deepracer_msgs/share ROS path [4]=/opt/ros/melodic/share process[servo_commands-7]: started with pid [19300] [ INFO] [1636338883.022119558]: Finished loading Gazebo ROS API Plugin. [ INFO] [1636338883.023514830]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting... [ INFO] [1636338883.030199443]: Finished loading Gazebo ROS API Plugin. [ INFO] [1636338883.031334300]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting... process[better_odom-8]: started with pid [19307] Traceback (most recent call last): File "/opt/install/Deepracer_Gazebo_Simulator/simulation_ws/install/deepracer_simulation/lib/deepracer_simulation/servo_commands.py", line 7, in from ackermann_msgs.msg import AckermannDriveStamped ImportError: No module named ackermann_msgs.msg [INFO] [1636338883.177870, 0.000000]: Controller Spawner: Waiting for service controller_manager/load_controller [ INFO] [1636338883.209596140]: waitForService: Service [/gazebo/set_physics_properties] is now available. [ INFO] [1636338883.224065129]: Physics dynamic reconfigure ready. [servo_commands-7] process has died [pid 19300, exit code 1, cmd /opt/install/Deepracer_Gazebo_Simulator/simulation_ws/install/deepracer_simulation/lib/deepracer_simulation/servo_commands.py /racecar/ackermann_cmd_mux/output:=/vesc/low_level/ackermann_cmd_mux/output __name:=servo_commands __log:=/root/.ros/log/6d473286-403c-11ec-b548-0242ac110002/servo_commands-7.log]. log file: /root/.ros/log/6d473286-403c-11ec-b548-0242ac110002/servo_commands-7*.log [INFO] [1636338883.443967, 0.000000]: Loading model XML from ros parameter robot_description [INFO] [1636338883.450150, 0.000000]: Waiting for service /gazebo/spawn_urdf_model [INFO] [1636338883.452360, 0.000000]: Calling service /gazebo/spawn_urdf_model [INFO] [1636338883.630170, 0.354000]: Spawn status: SpawnModel: Successfully spawned entity [ INFO] [1636338883.648277084, 0.354000000]: Loading gazebo_ros_control plugin [ INFO] [1636338883.648383753, 0.354000000]: Starting gazebo_ros_control plugin in namespace: /racecar [ INFO] [1636338883.648808355, 0.354000000]: gazebo_ros_control plugin is waiting for model URDF in parameter [/robot_description] on the ROS param server. Segmentation fault (core dumped) [gazebo_gui-3] process has died [pid 19233, exit code 139, cmd /opt/ros/melodic/lib/gazebo_ros/gzclient __name:=gazebo_gui __log:=/root/.ros/log/6d473286-403c-11ec-b548-0242ac110002/gazebo_gui-3.log]. log file: /root/.ros/log/6d473286-403c-11ec-b548-0242ac110002/gazebo_gui-3*.log [ WARN] [1636338883.758633311, 0.354000000]: Deprecated syntax, please prepend 'hardware_interface/' to 'EffortJointInterface' within the tag in joint 'left_rear_wheel_joint'. [ WARN] [1636338883.759353511, 0.354000000]: Deprecated syntax, please prepend 'hardware_interface/' to 'EffortJointInterface' within the tag in joint 'right_rear_wheel_joint'. [ WARN] [1636338883.759677192, 0.354000000]: Deprecated syntax, please prepend 'hardware_interface/' to 'EffortJointInterface' within the tag in joint 'left_steering_hinge_joint'. [ WARN] [1636338883.759944569, 0.354000000]: Deprecated syntax, please prepend 'hardware_interface/' to 'EffortJointInterface' within the tag in joint 'right_steering_hinge_joint'. [ WARN] [1636338883.760221676, 0.354000000]: Deprecated syntax, please prepend 'hardware_interface/' to 'EffortJointInterface' within the tag in joint 'left_front_wheel_joint'. [ WARN] [1636338883.760429437, 0.354000000]: Deprecated syntax, please prepend 'hardware_interface/' to 'EffortJointInterface' within the tag in joint 'right_front_wheel_joint'. [ INFO] [1636338883.763059896, 0.354000000]: Loaded gazebo_ros_control. ******* World name is: hard_track ********* [INFO] [1636338883.781887, 0.367000]: Controller Spawner: Waiting for service controller_manager/switch_controller [INFO] [1636338883.783763, 0.369000]: Controller Spawner: Waiting for service controller_manager/unload_controller [INFO] [1636338883.785333, 0.371000]: Loading controller: left_rear_wheel_velocity_controller [ERROR] [1636338883.787583493, 0.373000000]: Could not load controller 'left_rear_wheel_velocity_controller' because controller type 'effort_controllers/JointVelocityController' does not exist. [ERROR] [1636338883.787624385, 0.373000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types [racecar_spawn-4] process has finished cleanly log file: /root/.ros/log/6d473286-403c-11ec-b548-0242ac110002/racecar_spawn-4*.log [ERROR] [1636338884.788690, 1.373000]: Failed to load left_rear_wheel_velocity_controller [INFO] [1636338884.790131, 1.374000]: Loading controller: right_rear_wheel_velocity_controller [ERROR] [1636338884.792730122, 1.377000000]: Could not load controller 'right_rear_wheel_velocity_controller' because controller type 'effort_controllers/JointVelocityController' does not exist. [ERROR] [1636338884.792763911, 1.377000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types [ERROR] [1636338885.794029, 2.376000]: Failed to load right_rear_wheel_velocity_controller [INFO] [1636338885.795082, 2.377000]: Loading controller: left_front_wheel_velocity_controller [ERROR] [1636338885.797091131, 2.379000000]: Could not load controller 'left_front_wheel_velocity_controller' because controller type 'effort_controllers/JointVelocityController' does not exist. [ERROR] [1636338885.797134029, 2.379000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types [ERROR] [1636338886.798109, 3.379000]: Failed to load left_front_wheel_velocity_controller [INFO] [1636338886.799236, 3.380000]: Loading controller: right_front_wheel_velocity_controller [ERROR] [1636338886.801278064, 3.382000000]: Could not load controller 'right_front_wheel_velocity_controller' because controller type 'effort_controllers/JointVelocityController' does not exist. [ERROR] [1636338886.801301457, 3.382000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types [ERROR] [1636338887.802141, 4.381000]: Failed to load right_front_wheel_velocity_controller [INFO] [1636338887.803262, 4.382000]: Loading controller: left_steering_hinge_position_controller [ERROR] [1636338887.805312646, 4.384000000]: Could not load controller 'left_steering_hinge_position_controller' because controller type 'effort_controllers/JointPositionController' does not exist. [ERROR] [1636338887.805339247, 4.384000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types [ERROR] [1636338888.806109, 5.384000]: Failed to load left_steering_hinge_position_controller [INFO] [1636338888.807202, 5.385000]: Loading controller: right_steering_hinge_position_controller [ERROR] [1636338888.809172104, 5.387000000]: Could not load controller 'right_steering_hinge_position_controller' because controller type 'effort_controllers/JointPositionController' does not exist. [ERROR] [1636338888.809195991, 5.387000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types [ERROR] [1636338889.810089, 6.386000]: Failed to load right_steering_hinge_position_controller [INFO] [1636338889.811059, 6.387000]: Loading controller: joint_state_controller [ERROR] [1636338889.812874163, 6.389000000]: Could not load controller 'joint_state_controller' because controller type 'joint_state_controller/JointStateController' does not exist. [ERROR] [1636338889.812899368, 6.389000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types [ERROR] [1636338890.814110, 7.388000]: Failed to load joint_state_controller [INFO] [1636338890.815278, 7.390000]: Controller Spawner: Loaded controllers: [INFO] [1636338890.818296, 7.393000]: Started controllers: ^C[better_odom-8] killing on exit [racecar/controller_manager-5] killing on exit [gazebo-2] killing on exit [INFO] [1636338966.230223, 82.678000]: Shutting down spawner. Stopping and unloading controllers... [INFO] [1636338966.231931, 82.680000]: Stopping all controllers... [racecar/controller_manager-5] escalating to SIGTERM [gazebo-2] escalating to SIGTERM [WARN] [1636338981.252516, 82.680000]: Controller Spawner error while taking down controllers: transport error completing service call: receive_once[/racecar/controller_manager/switch_controller]: unexpected error [Errno 4] Interrupted system call [rosout-1] killing on exit [master] killing on exit shutting down processing monitor... ... shutting down processing monitor complete done

I ran the roslaunch command in the docker container and got this error

**Comment by Currycurrycurry** [comment]
`Segmentation fault (core dumped)
[gazebo_gui-3] process has died [pid 19233, exit code 139, cmd /opt/ros/melodic/lib/gazebo_ros/gzclient __name:=gazebo_gui __log:=/root/.ros/log/6d473286-403c-11ec-b548-0242ac110002/gazebo_gui-3.log].
log file: /root/.ros/log/6d473286-403c-11ec-b548-0242ac110002/gazebo_gui-3*.log`

And this is the main error.

**Comment by larsll** [comment]
There is no track named `hard_track`; this is why it fails.

**Comment by Currycurrycurry** [comment]
> There is no track named `hard_track`; this is why it fails.
I just edited the roslaunch file myself, deleting the useless part of the original file.
'<arg name="world_name" />
  <include file="$(find deepracer_simulation)/launch/racecar.launch">
    <arg name="world_name" value="$(arg world_name)"/>
  </include>'

**Comment by Currycurrycurry** [comment]
![image](https://user-images.githubusercontent.com/34653387/140725867-fed57135-cf9d-4a8c-aa94-fba2aa37f7ab.png)
@larsll
